### ISSUE TITLE
twitter bot

### ISSUE THREAD

**Issue by TheGurus** [datatau-net/DataTau#10]
idea: a simple script that getting twitter api details from settings, runs periodically (for example using django-crontab) and tweet news that reach front page. Tweeted news must be marked as 'tweeted' somehow to avoid tweeting it over and over again (for example adding a new boolean column in models.py)

**Comment by pedro-munoz** [comment]
approach: once a day, the bot will query the first 10 tweets from the frontpage. Then it will published the first one it is not already tweeted.

**Comment by pedro-munoz** [comment]
add Twitter accounts to retweet and like page posts
