### ISSUE TITLE
Add functionality to KDNuggets scraper

### ISSUE THREAD

**Issue by pedro-munoz** [datatau-net/DataTau#25]
Add more websites or search deeply on KDNuggets to keep the 1 post/day flow

**Comment by ravimashru** [comment]
There's a long list of potential sources here: https://www.kdnuggets.com/2019/01/active-blogs-ai-analytics-data-science.html

**Comment by pedro-munoz** [comment]
thanks Ravi, we're going to move this task to a private repo since it is not strictly related with DataTau website and the code will not be here (credentials issues)
