### ISSUE TITLE
improve post ordering in frontpage and transition from news to frontpage

### ISSUE THREAD

**Issue by TheGurus** [datatau-net/DataTau#7]
idea: set up proper rules for a post to be moved from news to front page, based on:
* time from posting
* upvotes
* user karma (user who post and voters)
* etc.

**Comment by dcanones** [comment]
Implemented new ranking algorithm inspired by HN (https://medium.com/hacking-and-gonzo/how-hacker-news-ranking-algorithm-works-1d9b0cf2c08d) based on upvotes, and time since submission, please give us your feedback.

```python
def post_sort_key(post_object):

    n_upvotes = post_object.votes

    lapse = timezone.now() - post_object.insert_date
    days = lapse.days
    hours, remainder = divmod(lapse.seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    hours_since_submission = days * 24 + hours + minutes / 60 + seconds / 3600

    score = (n_upvotes - 1) / (hours_since_submission + 2) ** settings.G
    log.info(f"ranking score for post {post_object.title} is: {score}")
    return score
```
